"""Add Game model

Revision ID: f3c177f63421
Revises: 3c1951258ec7
Create Date: 2025-09-25 18:47:47.253978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c177f63421'
down_revision = '3c1951258ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('api_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('api_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
