"""Add Game model

Revision ID: 3c1951258ec7
Revises: 30822eb97103
Create Date: 2025-09-25 18:40:59.631665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1951258ec7'
down_revision = '30822eb97103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('home_team', sa.String(length=100), nullable=True),
    sa.Column('visitor_team', sa.String(length=100), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('visitor_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
